# ===============================
# APP CONFIG
# ===============================
spring.application.name=rstp
server.port=8084

# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_db
spring.datasource.username=postgres
spring.datasource.password=sneha123

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL (optional but good)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=shippingTrackingPlatformSecretKeyForJWTSigning2026
jwt.expiration=86400000

# ===============================
# LOGGING
# ===============================
logging.level.com.infotact=DEBUG
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=DEBUG
